spring:
  application:
    name: mallapi
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: spring
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    sql: trace
    com:
      zaxxer: trace
